// Package workitem — scheduling: claim / heartbeat / release / start /
// retry / repair. M2.2 (实施计划 §M2.2, 方案 §6.4 + §15.3).
//
// Lease files live at .devsys/scheduling/<workitem-id>.yaml, written
// atomically alongside the workitem YAML and the audit event inside ONE
// storage.Write. ReconcileM2 inspects the scheduling/ directory directly.
//
// Fencing tokens: 16 random bytes hex-encoded (32 chars). Generated by
// Claim; never reused across claims. Every lease-bearing call (Heartbeat /
// Release / Update for a leased workitem / Run update against a leased
// workitem) MUST present the same Owner+Token currently recorded on the
// lease. Mismatches return ErrLeaseTokenMismatch.
//
// Status semantics enforced here:
//   - Claim:  ready / retry_queued / released-claimed (scheduler re-claim)
//     → in_progress ; writes lease + run + one combined event.
//   - Heartbeat: extends lease; status untouched.
//   - Release: removes lease; sets scheduling_state according to the
//     workitem's terminal position so the next Claim sees the
//     correct slot. Never demotes workitem.Status.
//   - Start: blocked→in_progress or retry_queued→running. Creates a Run
//     if absent.
//   - QueueRetry: in_progress / failed → retry_queued with deterministic
//     next_attempt_at.
//   - Repair: ApplyRepair is the only downward-completion path.
package workitem

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"workloom/internal/domain"
	"workloom/internal/events"
	runpkg "workloom/internal/run"
	"workloom/internal/storage"
)

// SchedulingDirName mirrors storage.SchedulingDirName; both sides agree
// on "scheduling".
const SchedulingDirName = "scheduling"

// DefaultLeaseDuration is the time a Claim writes into lease_until if the
// caller did not set ClaimOptions.LeaseDuration. Reconcile treats anything
// past lease_until as expired.
const DefaultLeaseDuration = 5 * time.Minute

// SchedulingStateMapping is the canonical (§6.4) table the runtime uses to
// derive SchedulingState when a lease is cleared. Keep it small and
// explicit so the audit trail reflects intent.
var SchedulingStateMapping = map[string]string{
	domain.StatusReady:        domain.SchedulingUnclaimed,
	domain.StatusInProgress:   domain.SchedulingUnclaimed,
	domain.StatusReview:       domain.SchedulingReleased,
	domain.StatusVerification: domain.SchedulingReleased,
	domain.StatusDone:         domain.SchedulingReleased,
	domain.StatusCancelled:    domain.SchedulingReleased,
	domain.StatusBlocked:      domain.SchedulingUnclaimed,
	domain.StatusBacklog:      domain.SchedulingUnclaimed,
	domain.StatusDraft:        domain.SchedulingUnclaimed,
}

// ClaimOptions is the input to Claim.
type ClaimOptions struct {
	Owner         string // required; identity of the claimer
	Token         string // IGNORED — every claim gets a fresh token.
	Expected      []byte
	HeadSHA       string
	LeaseDuration time.Duration
	Agent         domain.RunAgent
	WorkflowID    string
	Actor         string
	Reason        string
	Now           time.Time
}

// ClaimResult is the output of a successful Claim.
type ClaimResult struct {
	RunID  string
	Token  string
	Lease  domain.SchedulingLease
	Status string
}

// LeaseRef is the read-only pointer reconcile consumes. Path is the
// managed path relative to .devsys (slash-separated).
type LeaseRef struct {
	WorkitemID string
	Path       string
}

// ReleaseOptions is the input to Release.
type ReleaseOptions struct {
	Owner      string
	Token      string
	Expected   []byte
	ForExpired bool // require verified lease_until < now; skip owner/token
	ForOrphan  bool // require lease exists AND its run file is missing
	Actor      string
	Reason     string
	Now        time.Time
}

// HeartbeatOptions is the input to Heartbeat.
type HeartbeatOptions struct {
	Owner    string
	Token    string
	Expected []byte
	ExtendBy time.Duration
	Actor    string
	Reason   string
	Now      time.Time
}

// StartOptions transitions a blocked / retry_queued workitem into
// in_progress and stages a new Run if none exists. Expected is required.
type StartOptions struct {
	Owner         string
	Token         string
	Expected      []byte
	HeadSHA       string
	LeaseDuration time.Duration
	Agent         domain.RunAgent
	WorkflowID    string
	Actor         string
	Reason        string
	Now           time.Time
}

// StartResult is the output of Start.
type StartResult struct {
	RunID string
	Token string
	Lease domain.SchedulingLease
}

// RetryOptions re-queues an in_progress workitem for another attempt.
// Expected is required; owner/token must match the active lease.
type RetryOptions struct {
	Owner     string
	Token     string
	Expected  []byte
	BaseDelay time.Duration // default 1 min; deterministic scaling on attempt
	Attempt   int           // next attempt number; must be > current lease attempt
	Actor     string
	Reason    string
	Now       time.Time
}

// RetryResult records the deterministic next_attempt_at used.
type RetryResult struct {
	NextAttemptAt time.Time
}

// Claim atomically:
//  1. Creates a fresh run record via run.CreateTx inside the same Write.
//  2. Writes .devsys/scheduling/<id>.yaml with a new random token +
//     lease_until = now + LeaseDuration.
//  3. Writes .devsys/workitems/<id>.yaml with status=in_progress,
//     scheduling_state=claimed, lease_owner, lease_token, lease_* fields.
//  4. Appends ONE combined "claimed" event (no second append_jsonl to
//     the same shard in one tx).
//
// Preconditions:
//   - Status must be ready, retry_queued or released (re-claim after
//     review/verification handback). Other current statuses return a
//     *domain.TransitionError carrying the allowed list.
//   - If a lease file already exists, return ErrAlreadyClaimed.
//
// Concurrency: the lease file is created with ExpectAbsent; two Claims on
// the same work item see exactly one winner. The loser sees
// ErrAlreadyClaimed (storage.ErrConflict is mapped).
func (s *Store) Claim(ctx context.Context, id string, opts ClaimOptions) (ClaimResult, error) {
	if err := requiredFields(opts.Owner, opts.Actor, opts.Reason); err != nil {
		return ClaimResult{}, err
	}
	if !ValidID(id) {
		return ClaimResult{}, fmt.Errorf("%w: %q", ErrBadPrefix, id)
	}

	now := opts.Now
	if now.IsZero() {
		now = time.Now().UTC()
	}
	dur := opts.LeaseDuration
	if dur <= 0 {
		dur = DefaultLeaseDuration
	}
	token, err := newToken()
	if err != nil {
		return ClaimResult{}, fmt.Errorf("generate claim token: %w", err)
	}

	cur, snap, err := s.ReadSnapshot(ctx, id)
	if err != nil {
		return ClaimResult{}, err
	}
	if len(opts.Expected) > 0 && !bytesEqual(opts.Expected, snap) {
		return ClaimResult{}, fmt.Errorf("%w: workitem %s changed concurrently", storage.ErrConflict, id)
	}
	// Re-claim after a prior review/verification handback is allowed only
	// when the lease file is gone (the prior claimer released it). If a
	// lease still exists we treat the work item as claimed.
	leaseStillHeld, err := leaseFilePresent(s, id)
	if err != nil {
		return ClaimResult{}, err
	}
	if leaseStillHeld {
		return ClaimResult{}, ErrAlreadyClaimed
	}

	switch cur.Status {
	case domain.StatusReady, domain.StatusBacklog, "retry_queued", domain.StatusReview, domain.StatusVerification:
		// ok
	default:
		if cur.SchedulingState == domain.SchedulingClaimed ||
			cur.SchedulingState == domain.SchedulingRunning {
			return ClaimResult{}, ErrAlreadyClaimed
		}
	}
	if !domain.IsTransitionLegal(cur.Status, domain.StatusInProgress) &&
		cur.Status != "retry_queued" {
		return ClaimResult{}, &domain.TransitionError{
			From: cur.Status, To: domain.StatusInProgress,
			Allowed: domain.AllowedFrom(cur.Status),
			Reason:  "claim requires status=ready, retry_queued, or post-review/verification re-claim",
		}
	}

	run := &domain.Run{
		SchemaVersion: domain.SchemaVersion,
		ProjectID:     cur.ProjectID,
		WorkItemID:    id,
		WorkflowID:    opts.WorkflowID,
		Agent:         opts.Agent,
		Status:        "running",
		Attempt:       1,
		Phase:         "claimed",
		StartedAt:     now,
	}

	st, err := s.store()
	if err != nil {
		return ClaimResult{}, err
	}
	if err := ensureEventsDir(st.DevsysDir()); err != nil {
		return ClaimResult{}, fmt.Errorf("create events directory: %w", err)
	}
	prevStatus := cur.Status
	cur.Status = domain.StatusInProgress
	cur.SchedulingState = domain.SchedulingClaimed
	cur.UpdatedAt = now

	ev := &domain.Event{
		SchemaVersion: domain.SchemaVersion,
		ProjectID:     cur.ProjectID,
		Type:          "claimed",
		Subject:       domain.Reference{Type: "workitem", ID: id},
		Time:          now,
		Actor:         opts.Actor,
		Content:       fmt.Sprintf("claimed by %s: %s \u2192 %s; %s", opts.Owner, prevStatus, domain.StatusInProgress, opts.Reason),
	}

	err = st.Write(ctx, func(tx *storage.Tx) error {
		if err := runpkg.New(s.root).CreateTx(tx, run); err != nil {
			return fmt.Errorf("create run: %w", err)
		}
		lease := domain.SchedulingLease{
			SchemaVersion: domain.SchemaVersion,
			WorkItemID:    id,
			Owner:         opts.Owner,
			Token:         token,
			ClaimedAt:     now,
			LeaseUntil:    now.Add(dur),
			HeartbeatAt:   now,
			HeadSHA:       opts.HeadSHA,
			RunID:         run.ID,
			AgentID:       opts.Agent.ID,
			AgentHarness:  opts.Agent.Harness,
		}
		cur.LeaseOwner = opts.Owner
		cur.LeaseToken = token
		cur.LeaseClaimedAt = &lease.ClaimedAt
		cur.LeaseUntil = &lease.LeaseUntil
		cur.HeartbeatAt = &lease.HeartbeatAt
		cur.ActiveRunID = run.ID
		ev.Related = []domain.Reference{{Type: "run", ID: run.ID}}
		if err := tx.PutYAML(leaseRel(id), lease, storage.ExpectAbsent()); err != nil {
			return err
		}
		if err := tx.PutYAML(workitemRel(id), cur, storage.ExpectHash(storage.HashBytes(snap))); err != nil {
			return err
		}
		return events.AppendTx(tx, ev)
	})
	if err != nil {
		if errors.Is(err, storage.ErrConflict) {
			return ClaimResult{}, ErrAlreadyClaimed
		}
		return ClaimResult{}, err
	}
	return ClaimResult{
		RunID:  run.ID,
		Token:  token,
		Status: domain.StatusInProgress,
		Lease: domain.SchedulingLease{
			SchemaVersion: domain.SchemaVersion,
			WorkItemID:    id,
			Owner:         opts.Owner,
			Token:         token,
			ClaimedAt:     now,
			LeaseUntil:    now.Add(dur),
			HeartbeatAt:   now,
			HeadSHA:       opts.HeadSHA,
			RunID:         run.ID,
			AgentID:       opts.Agent.ID,
			AgentHarness:  opts.Agent.Harness,
		},
	}, nil
}

// Heartbeat extends the lease on a work item whose lease is still active
// and still owned by the caller. Mismatching owner/token or an expired
// lease returns ErrLeaseTokenMismatch / ErrLeaseExpired.
func (s *Store) Heartbeat(ctx context.Context, id string, opts HeartbeatOptions) error {
	if strings.TrimSpace(opts.Owner) == "" || strings.TrimSpace(opts.Token) == "" {
		return fmt.Errorf("%w: owner and token are required", ErrInvalidInput)
	}
	if !ValidID(id) {
		return fmt.Errorf("%w: %q", ErrBadPrefix, id)
	}
	now := opts.Now
	if now.IsZero() {
		now = time.Now().UTC()
	}
	dur := opts.ExtendBy
	if dur <= 0 {
		dur = DefaultLeaseDuration
	}
	cur, snap, err := s.ReadSnapshot(ctx, id)
	if err != nil {
		return err
	}
	if len(opts.Expected) > 0 && !bytesEqual(opts.Expected, snap) {
		return fmt.Errorf("%w: workitem %s changed concurrently", storage.ErrConflict, id)
	}
	if cur.LeaseOwner == "" || cur.LeaseToken == "" {
		return ErrNotClaimed
	}
	if cur.LeaseOwner != opts.Owner || cur.LeaseToken != opts.Token {
		return ErrLeaseTokenMismatch
	}

	st, err := s.store()
	if err != nil {
		return err
	}
	if err := ensureEventsDir(st.DevsysDir()); err != nil {
		return fmt.Errorf("create events directory: %w", err)
	}
	return st.Write(ctx, func(tx *storage.Tx) error {
		leaseBytes, leaseExists, err := tx.ReadForExpect(leaseRel(id))
		if err != nil {
			return err
		}
		if !leaseExists {
			return ErrNotClaimed
		}
		var lease domain.SchedulingLease
		if err := domain.DecodeYAML(leaseBytes, &lease); err != nil {
			return fmt.Errorf("decode lease file: %w", err)
		}
		if lease.Owner != opts.Owner || lease.Token != opts.Token {
			return ErrLeaseTokenMismatch
		}
		if !lease.LeaseUntil.After(now) {
			return ErrLeaseExpired
		}
		lease.HeartbeatAt = now
		lease.LeaseUntil = now.Add(dur)
		newUntil := lease.LeaseUntil
		cur.LeaseUntil = &newUntil
		cur.HeartbeatAt = &now
		cur.UpdatedAt = now
		ev := &domain.Event{
			SchemaVersion: domain.SchemaVersion,
			ProjectID:     cur.ProjectID,
			Type:          "lease_heartbeat",
			Subject:       domain.Reference{Type: "workitem", ID: id},
			Time:          now,
			Actor:         opts.Actor,
			Content:       fmt.Sprintf("heartbeat until %s: %s", newUntil.Format(time.RFC3339Nano), opts.Reason),
		}
		if err := tx.PutYAML(workitemRel(id), cur, storage.ExpectHash(storage.HashBytes(snap))); err != nil {
			return err
		}
		if err := tx.PutYAML(leaseRel(id), lease, storage.ExpectHash(storage.HashBytes(leaseBytes))); err != nil {
			return err
		}
		return events.AppendTx(tx, ev)
	})
}

// Release removes the lease and adjusts the scheduling_state to match
// the workitem's logical position. ForExpired=true requires verified
// lease_until < now; ForOrphan=true requires the referenced Run file to
// be missing. Either flag bypasses owner/token. Status is never demoted.
func (s *Store) Release(ctx context.Context, id string, opts ReleaseOptions) error {
	if strings.TrimSpace(opts.Actor) == "" || strings.TrimSpace(opts.Reason) == "" {
		return fmt.Errorf("%w: actor and reason are required", ErrInvalidInput)
	}
	if !ValidID(id) {
		return fmt.Errorf("%w: %q", ErrBadPrefix, id)
	}
	now := opts.Now
	if now.IsZero() {
		now = time.Now().UTC()
	}
	cur, snap, err := s.ReadSnapshot(ctx, id)
	if err != nil {
		return err
	}
	if len(opts.Expected) > 0 && !bytesEqual(opts.Expected, snap) {
		return fmt.Errorf("%w: workitem %s changed concurrently", storage.ErrConflict, id)
	}

	st, err := s.store()
	if err != nil {
		return err
	}
	if err := ensureEventsDir(st.DevsysDir()); err != nil {
		return fmt.Errorf("create events directory: %w", err)
	}
	return st.Write(ctx, func(tx *storage.Tx) error {
		leaseBytes, leaseExists, err := tx.ReadForExpect(leaseRel(id))
		if err != nil {
			return err
		}
		if !leaseExists {
			return nil // idempotent
		}
		var lease domain.SchedulingLease
		if err := domain.DecodeYAML(leaseBytes, &lease); err != nil {
			return fmt.Errorf("decode lease file: %w", err)
		}

		if !opts.ForExpired && !opts.ForOrphan {
			if opts.Owner == "" || opts.Token == "" {
				return fmt.Errorf("%w: owner and token are required for non-recovery release", ErrInvalidInput)
			}
			if lease.Owner != opts.Owner || lease.Token != opts.Token {
				return ErrLeaseTokenMismatch
			}
		} else {
			if opts.ForExpired && !lease.LeaseUntil.Before(now) {
				return fmt.Errorf("%w: lease_until is not past now", ErrInvalidInput)
			}
			if opts.ForOrphan {
				runBytes, runExists, err := tx.ReadForExpect("runs/" + lease.RunID + ".yaml")
				if err != nil {
					return err
				}
				if runExists && len(runBytes) > 0 {
					return fmt.Errorf("%w: ForOrphan release requires run %s to be missing", ErrInvalidInput, lease.RunID)
				}
			}
		}

		cur.LeaseOwner = ""
		cur.LeaseToken = ""
		cur.LeaseClaimedAt = nil
		cur.LeaseUntil = nil
		cur.HeartbeatAt = nil
		// Map scheduling_state according to status (§6.4). Never demotes
		// the work item's status.
		next := SchedulingStateMapping[cur.Status]
		if next == "" {
			next = domain.SchedulingUnclaimed
		}
		cur.SchedulingState = next
		cur.UpdatedAt = now

		ev := &domain.Event{
			SchemaVersion: domain.SchemaVersion,
			ProjectID:     cur.ProjectID,
			Type:          "lease_released",
			Subject:       domain.Reference{Type: "workitem", ID: id},
			Time:          now,
			Actor:         opts.Actor,
			Content:       fmt.Sprintf("released lease %s: %s", lease.RunID, opts.Reason),
			Related:       []domain.Reference{{Type: "run", ID: lease.RunID}},
		}
		if opts.ForExpired {
			ev.Type = "lease_recovered"
			ev.Content = fmt.Sprintf("recovered expired lease (was until %s): %s", lease.LeaseUntil.Format(time.RFC3339Nano), opts.Reason)
		}
		if opts.ForOrphan {
			ev.Type = "lease_recovered"
			ev.Content = fmt.Sprintf("recovered orphan lease (run %s missing): %s", lease.RunID, opts.Reason)
		}

		// Close the associated Run atomically: status=finished, finished_at=now.
		if lease.RunID != "" {
			runBytes, runExists, err := tx.ReadForExpect("runs/" + lease.RunID + ".yaml")
			if err != nil {
				return err
			}
			if runExists && len(runBytes) > 0 {
				var run domain.Run
				if err := domain.DecodeYAML(runBytes, &run); err != nil {
					return fmt.Errorf("decode run %s: %w", lease.RunID, err)
				}
				run.Status = "finished"
				run.FinishedAt = &now
				if err := tx.PutYAML("runs/"+lease.RunID+".yaml", run, storage.ExpectHash(storage.HashBytes(runBytes))); err != nil {
					return err
				}
				ev.Related = append(ev.Related, domain.Reference{Type: "run_finished", ID: lease.RunID})
			}
		}

		if err := tx.PutYAML(workitemRel(id), cur, storage.ExpectHash(storage.HashBytes(snap))); err != nil {
			return err
		}
		if err := tx.Delete(leaseRel(id), storage.ExpectHash(storage.HashBytes(leaseBytes))); err != nil {
			return err
		}
		return events.AppendTx(tx, ev)
	})
}

// Start transitions a blocked or retry_queued work item into in_progress.
// Equivalent to a fresh Claim but enforces the source status and reuses
// the existing lease file when present (resume after pause).
func (s *Store) Start(ctx context.Context, id string, opts StartOptions) (StartResult, error) {
	if err := requiredFields(opts.Owner, opts.Actor, opts.Reason); err != nil {
		return StartResult{}, err
	}
	if !ValidID(id) {
		return StartResult{}, fmt.Errorf("%w: %q", ErrBadPrefix, id)
	}
	now := opts.Now
	if now.IsZero() {
		now = time.Now().UTC()
	}
	dur := opts.LeaseDuration
	if dur <= 0 {
		dur = DefaultLeaseDuration
	}

	cur, snap, err := s.ReadSnapshot(ctx, id)
	if err != nil {
		return StartResult{}, err
	}
	if len(opts.Expected) > 0 && !bytesEqual(opts.Expected, snap) {
		return StartResult{}, fmt.Errorf("%w: workitem %s changed concurrently", storage.ErrConflict, id)
	}
	switch cur.Status {
	case domain.StatusBlocked, "retry_queued":
		// ok
	default:
		return StartResult{}, &domain.TransitionError{
			From: cur.Status, To: domain.StatusInProgress,
			Allowed: domain.AllowedFrom(cur.Status),
			Reason:  "start requires blocked or retry_queued",
		}
	}

	token, err := newToken()
	if err != nil {
		return StartResult{}, fmt.Errorf("generate claim token: %w", err)
	}
	run := &domain.Run{
		SchemaVersion: domain.SchemaVersion,
		ProjectID:     cur.ProjectID,
		WorkItemID:    id,
		WorkflowID:    opts.WorkflowID,
		Agent:         opts.Agent,
		Status:        "running",
		Attempt:       1,
		Phase:         "started",
		StartedAt:     now,
	}
	prevStatus := cur.Status
	cur.Status = domain.StatusInProgress
	cur.SchedulingState = domain.SchedulingRunning
	cur.UpdatedAt = now
	st, err := s.store()
	if err != nil {
		return StartResult{}, err
	}
	if err := ensureEventsDir(st.DevsysDir()); err != nil {
		return StartResult{}, fmt.Errorf("create events directory: %w", err)
	}
	ev := &domain.Event{
		SchemaVersion: domain.SchemaVersion,
		ProjectID:     cur.ProjectID,
		Type:          "started",
		Subject:       domain.Reference{Type: "workitem", ID: id},
		Time:          now,
		Actor:         opts.Actor,
		Content:       fmt.Sprintf("started by %s: %s \u2192 %s; %s", opts.Owner, prevStatus, domain.StatusInProgress, opts.Reason),
	}
	err = st.Write(ctx, func(tx *storage.Tx) error {
		if err := runpkg.New(s.root).CreateTx(tx, run); err != nil {
			return fmt.Errorf("create run: %w", err)
		}
		lease := domain.SchedulingLease{
			SchemaVersion: domain.SchemaVersion,
			WorkItemID:    id,
			Owner:         opts.Owner,
			Token:         token,
			ClaimedAt:     now,
			LeaseUntil:    now.Add(dur),
			HeartbeatAt:   now,
			HeadSHA:       opts.HeadSHA,
			RunID:         run.ID,
			AgentID:       opts.Agent.ID,
			AgentHarness:  opts.Agent.Harness,
		}
		cur.LeaseOwner = opts.Owner
		cur.LeaseToken = token
		cur.LeaseClaimedAt = &lease.ClaimedAt
		cur.LeaseUntil = &lease.LeaseUntil
		cur.HeartbeatAt = &lease.HeartbeatAt
		cur.ActiveRunID = run.ID
		ev.Related = []domain.Reference{{Type: "run", ID: run.ID}}
		if err := tx.PutYAML(leaseRel(id), lease, storage.ExpectAbsent()); err != nil {
			return err
		}
		if err := tx.PutYAML(workitemRel(id), cur, storage.ExpectHash(storage.HashBytes(snap))); err != nil {
			return err
		}
		return events.AppendTx(tx, ev)
	})
	if err != nil {
		if errors.Is(err, storage.ErrConflict) {
			return StartResult{}, ErrAlreadyClaimed
		}
		return StartResult{}, err
	}
	return StartResult{
		RunID: run.ID,
		Token: token,
		Lease: domain.SchedulingLease{
			SchemaVersion: domain.SchemaVersion,
			WorkItemID:    id,
			Owner:         opts.Owner,
			Token:         token,
			ClaimedAt:     now,
			LeaseUntil:    now.Add(dur),
			HeartbeatAt:   now,
			HeadSHA:       opts.HeadSHA,
			RunID:         run.ID,
			AgentID:       opts.Agent.ID,
			AgentHarness:  opts.Agent.Harness,
		},
	}, nil
}

// QueueRetry moves an in_progress work item to retry_queued with a
// deterministic next_attempt_at = now + base * 2^(attempt-1) capped at
// 1 hour. Owner/token must match the current lease.
func (s *Store) QueueRetry(ctx context.Context, id string, opts RetryOptions) (RetryResult, error) {
	if strings.TrimSpace(opts.Owner) == "" || strings.TrimSpace(opts.Token) == "" {
		return RetryResult{}, fmt.Errorf("%w: owner and token are required", ErrInvalidInput)
	}
	if !ValidID(id) {
		return RetryResult{}, fmt.Errorf("%w: %q", ErrBadPrefix, id)
	}
	now := opts.Now
	if now.IsZero() {
		now = time.Now().UTC()
	}
	base := opts.BaseDelay
	if base <= 0 {
		base = time.Minute
	}
	cur, snap, err := s.ReadSnapshot(ctx, id)
	if err != nil {
		return RetryResult{}, err
	}
	if len(opts.Expected) > 0 && !bytesEqual(opts.Expected, snap) {
		return RetryResult{}, fmt.Errorf("%w: workitem %s changed concurrently", storage.ErrConflict, id)
	}
	if cur.LeaseOwner == "" || cur.LeaseToken == "" {
		return RetryResult{}, ErrNotClaimed
	}
	if cur.LeaseOwner != opts.Owner || cur.LeaseToken != opts.Token {
		return RetryResult{}, ErrLeaseTokenMismatch
	}
	if cur.Status != domain.StatusInProgress {
		return RetryResult{}, &domain.TransitionError{
			From: cur.Status, To: "retry_queued",
			Allowed: domain.AllowedFrom(cur.Status),
			Reason:  "QueueRetry requires in_progress",
		}
	}
	attempt := opts.Attempt
	if attempt <= 0 {
		attempt = 1
	}
	delay := base
	for i := 1; i < attempt; i++ {
		delay *= 2
		if delay > time.Hour {
			delay = time.Hour
			break
		}
	}
	next := now.Add(delay)
	cur.Status = "retry_queued"
	cur.SchedulingState = domain.SchedulingRetryQueued
	cur.LeaseOwner = ""
	cur.LeaseToken = ""
	cur.LeaseClaimedAt = nil
	cur.LeaseUntil = nil
	cur.HeartbeatAt = nil
	cur.UpdatedAt = now
	cur.NextAttemptAt = &next

	st, err := s.store()
	if err != nil {
		return RetryResult{}, err
	}
	if err := ensureEventsDir(st.DevsysDir()); err != nil {
		return RetryResult{}, fmt.Errorf("create events directory: %w", err)
	}
	leaseBytes, leaseExists, lerr := s.readLeaseBytes(st, id)
	if lerr != nil {
		return RetryResult{}, lerr
	}
	if !leaseExists {
		return RetryResult{}, ErrNotClaimed
	}
	ev := &domain.Event{
		SchemaVersion: domain.SchemaVersion,
		ProjectID:     cur.ProjectID,
		Type:          "retry_queued",
		Subject:       domain.Reference{Type: "workitem", ID: id},
		Time:          now,
		Actor:         opts.Actor,
		Content:       fmt.Sprintf("retry queued at %s (attempt %d): %s", next.Format(time.RFC3339Nano), attempt, opts.Reason),
	}
	err = st.Write(ctx, func(tx *storage.Tx) error {
		if err := tx.PutYAML(workitemRel(id), cur, storage.ExpectHash(storage.HashBytes(snap))); err != nil {
			return err
		}
		if err := tx.Delete(leaseRel(id), storage.ExpectHash(storage.HashBytes(leaseBytes))); err != nil {
			return err
		}
		return events.AppendTx(tx, ev)
	})
	if err != nil {
		return RetryResult{}, err
	}
	return RetryResult{NextAttemptAt: next}, nil
}

// UpdateClaimed updates a leased workitem's metadata (title, description,
// etc.) while requiring the caller to present the current lease
// owner/token. The status field stays fenced via Update's check; only
// non-status fields are mutable through this entry point.
func (s *Store) UpdateClaimed(ctx context.Context, id, owner, token string, mutate func(*domain.WorkItem), expected []byte) error {
	if !ValidID(id) {
		return fmt.Errorf("%w: %q", ErrBadPrefix, id)
	}
	if strings.TrimSpace(owner) == "" || strings.TrimSpace(token) == "" {
		return fmt.Errorf("%w: owner and token are required", ErrInvalidInput)
	}
	cur, snap, err := s.ReadSnapshot(ctx, id)
	if err != nil {
		return err
	}
	if len(expected) > 0 && !bytesEqual(expected, snap) {
		return fmt.Errorf("%w: workitem %s changed concurrently", storage.ErrConflict, id)
	}
	if cur.LeaseOwner == "" || cur.LeaseToken == "" {
		return ErrNotClaimed
	}
	if cur.LeaseOwner != owner || cur.LeaseToken != token {
		return ErrLeaseTokenMismatch
	}
	prevStatus := cur.Status
	prevState := cur.SchedulingState
	prevOwner := cur.LeaseOwner
	prevToken := cur.LeaseToken
	prevClaimed := cur.LeaseClaimedAt
	prevUntil := cur.LeaseUntil
	prevHeartbeat := cur.HeartbeatAt
	prevRun := cur.ActiveRunID

	mutate(cur)

	// Re-fence every scheduling field so a misuse of mutate cannot bypass
	// the lease. This is a defense in depth on top of Update's check.
	cur.Status = prevStatus
	cur.SchedulingState = prevState
	cur.LeaseOwner = prevOwner
	cur.LeaseToken = prevToken
	cur.LeaseClaimedAt = prevClaimed
	cur.LeaseUntil = prevUntil
	cur.HeartbeatAt = prevHeartbeat
	cur.ActiveRunID = prevRun

	st, err := s.store()
	if err != nil {
		return err
	}
	return st.Write(ctx, func(tx *storage.Tx) error {
		return tx.PutYAML(workitemRel(id), cur, storage.ExpectHash(storage.HashBytes(snap)))
	})
}

// LeaseInspection returns the parsed lease for the work item, or
// ErrNotClaimed when no lease file is present.
func (s *Store) LeaseInspection(ctx context.Context, id string) (domain.SchedulingLease, error) {
	if !ValidID(id) {
		return domain.SchedulingLease{}, fmt.Errorf("%w: %q", ErrBadPrefix, id)
	}
	st, err := s.store()
	if err != nil {
		return domain.SchedulingLease{}, err
	}
	var (
		data  []byte
		found bool
	)
	if err := st.Read(ctx, func(r *storage.Reader) error {
		b, e, err := r.Read(leaseRel(id))
		if err != nil {
			return err
		}
		if e {
			data = append([]byte(nil), b...)
			found = true
		}
		return nil
	}); err != nil {
		return domain.SchedulingLease{}, err
	}
	if !found {
		return domain.SchedulingLease{}, ErrNotClaimed
	}
	var lease domain.SchedulingLease
	if err := domain.DecodeYAML(data, &lease); err != nil {
		return domain.SchedulingLease{}, err
	}
	return lease, nil
}

// ListLeases enumerates every lease file under .devsys/scheduling/. It
// is read-only; reconcile may call it directly.
func (s *Store) ListLeases(ctx context.Context) ([]LeaseRef, error) {
	st, err := s.store()
	if err != nil {
		return nil, err
	}
	var out []LeaseRef
	err = st.Read(ctx, func(r *storage.Reader) error {
		entries, err := listSchedulingEntries(st.DevsysDir())
		if err != nil {
			return err
		}
		for _, id := range entries {
			if !ValidID(id) {
				continue
			}
			out = append(out, LeaseRef{WorkitemID: id, Path: SchedulingDirName + "/" + id + ".yaml"})
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FenceRunUpdate guards run mutations on a leased workitem: run updates
// must present the current lease owner/token. The caller passes the
// pre-read run bytes; we re-validate the lease under the same transaction
// to avoid stale snapshots.
func (s *Store) FenceRunUpdate(ctx context.Context, workitemID, owner, token string, mutate func(*domain.Run), expected []byte) error {
	if !ValidID(workitemID) {
		return fmt.Errorf("%w: %q", ErrBadPrefix, workitemID)
	}
	if strings.TrimSpace(owner) == "" || strings.TrimSpace(token) == "" {
		return fmt.Errorf("%w: owner and token are required", ErrInvalidInput)
	}
	st, err := s.store()
	if err != nil {
		return err
	}
	return st.Write(ctx, func(tx *storage.Tx) error {
		leaseBytes, leaseExists, err := tx.ReadForExpect(leaseRel(workitemID))
		if err != nil {
			return err
		}
		if !leaseExists {
			return ErrNotClaimed
		}
		var lease domain.SchedulingLease
		if err := domain.DecodeYAML(leaseBytes, &lease); err != nil {
			return fmt.Errorf("decode lease: %w", err)
		}
		if lease.Owner != owner || lease.Token != token {
			return ErrLeaseTokenMismatch
		}
		runBytes, runExists, err := tx.ReadForExpect("runs/" + lease.RunID + ".yaml")
		if err != nil {
			return err
		}
		if !runExists {
			return fmt.Errorf("run %s missing", lease.RunID)
		}
		var run domain.Run
		if err := domain.DecodeYAML(runBytes, &run); err != nil {
			return fmt.Errorf("decode run: %w", err)
		}
		mutate(&run)
		return tx.PutYAML("runs/"+lease.RunID+".yaml", run, storage.ExpectHash(storage.HashBytes(runBytes)))
	})
}

// newToken returns 16 random bytes hex-encoded (32 chars).
func newToken() (string, error) {
	var rnd [16]byte
	if _, err := rand.Read(rnd[:]); err != nil {
		return "", err
	}
	return hex.EncodeToString(rnd[:]), nil
}

// leaseRel returns the managed path for a work item's lease file.
func leaseRel(id string) string {
	return SchedulingDirName + "/" + id + ".yaml"
}

// readLeaseBytes returns the lease file bytes (nil if missing) and a
// presence flag. Read-only — the caller wraps the call in a Write when
// CAS is required.
func (s *Store) readLeaseBytes(st *storage.Store, id string) ([]byte, bool, error) {
	var (
		data  []byte
		found bool
	)
	err := st.Read(context.Background(), func(r *storage.Reader) error {
		b, e, err := r.Read(leaseRel(id))
		if err != nil {
			return err
		}
		if e {
			data = append([]byte(nil), b...)
			found = true
		}
		return nil
	})
	if err != nil {
		return nil, false, err
	}
	return data, found, nil
}

// leaseFilePresent is the cheap pre-check Claim runs before scanning the
// directory.
func leaseFilePresent(s *Store, id string) (bool, error) {
	st, err := s.store()
	if err != nil {
		return false, err
	}
	_, found, err := s.readLeaseBytes(st, id)
	return found, err
}

// listSchedulingEntries returns the names (no extension) of every file in
// .devsys/scheduling/, in ascending lexical order.
func listSchedulingEntries(devsysDir string) ([]string, error) {
	dir := devsysDir + "/" + SchedulingDirName
	entries, err := os.ReadDir(dir)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, nil
		}
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".yaml") {
			continue
		}
		id := strings.TrimSuffix(name, ".yaml")
		out = append(out, id)
	}
	sortStrings(out)
	return out, nil
}

// requiredFields is a small validation helper shared by Claim/Start.
func requiredFields(fields ...string) error {
	for _, f := range fields {
		if strings.TrimSpace(f) == "" {
			return fmt.Errorf("%w: required field is empty", ErrInvalidInput)
		}
	}
	return nil
}

// keep filepath import alive for tools that strip unused imports.
var _ = filepath.Join
